version: '3.9'

services:
  backend:
    image: node:18
    working_dir: /app
    volumes:
      - ./backend:/app
    env_file:
      - .env
    environment:
      - PORT=3001
    command: sh -c "npm install && npm run dev"
    ports:
      - '3001:3001'

  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
    environment:
      - VITE_BACKEND_URL=http://backend:3001
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 3000"
    ports:
      - '3000:3000'
    depends_on:
      - backend
