version: '3.9'

services:
  backend:
    build:
      context: ./backend
    command: npm run dev
    ports:
      - "4000:4000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - backend-node-modules:/app/node_modules
    working_dir: /app
    depends_on: []

  frontend:
    build:
      context: ./frontend
    command: npm run dev -- --host 0.0.0.0 --port 5173
    ports:
      - "5173:5173"
    env_file:
      - .env
    environment:
      - VITE_API_BASE_URL=http://backend:4000
    volumes:
      - ./frontend:/app
      - frontend-node-modules:/app/node_modules
    working_dir: /app
    depends_on:
      - backend

volumes:
  backend-node-modules:
  frontend-node-modules:
